language: node_js
sudo: required
node_js: stable
addons:
  firefox: '46.0'
  sauce_connect: true
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install -g bower polylint web-component-tester
  - bower install
  - polylint
script:
  - xvfb-run wct
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then wct -s 'default'; fi"
env:
  global:
    - secure: DUM7LFRJH7Ji78bVRep6D3rJ+RH8F1Y15gSaCZ5SvlJ8lMuTYmpCVZ876LHVHdOv28d5dyPDn3U3slvssDO5UldTzZDNALX6/mOncY6QxRIbz+0E6Fm5Vn3PUXkBop/k/ELgCwmSDBfXGeKeRIu7nc/nDBldiMiwrHtyXTeuE+c=
    - secure: DqAN8qB45TWPfGVtrttAUV3fOu97j3qOnAUj+QxawlqBySqj3fcAD49HZFgQuBNMi0gxGYqrAAYj6AAyqIxH+K8P3PHPRfVegyRfYA4dcohnG9zYKmV5M+SaZEYpFp1FBXl3aKGbk0qiBmMsHWM2trkdRNNVAUl09Ywozapdpq8=
dist: trusty
